language: scala

jdk:
- openjdk8
- openjdk11

script:
  - sbt +publishLocal

cache:
  directories:
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.cache/coursier
before_cache:
  - rm -rf $HOME/.ivy2/local
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
