name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 16]
        scala: [2.11.12, 2.12.13, 2.13.5]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - name: Test
      run: sbt ++${{matrix.scala}} publishLocal
